# Generated by Django 3.1.7 on 2021-04-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Photos',
            new_name='Notice',
        ),
        migrations.RenameModel(
            old_name='Notices',
            new_name='Photo',
        ),
    ]
