# Generated by Django 3.1.7 on 2021-04-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_site', '0002_auto_20210402_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='Description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='notice',
            name='Heading',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
