# Generated by Django 3.1.7 on 2021-04-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_site', '0004_auto_20210402_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='Image',
            field=models.ImageField(default='', upload_to='Photos'),
            preserve_default=False,
        ),
    ]
