# Generated by Django 3.1.7 on 2021-07-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_site', '0005_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
            ],
        ),
    ]
