# Generated by Django 3.2.5 on 2021-07-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_site', '0007_headerimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='Message',
            field=models.TextField(default=''),
        ),
    ]
