# Generated by Django 3.2.5 on 2021-07-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_site', '0008_alter_feedbacks_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerimages',
            name='PAGE',
            field=models.CharField(choices=[('Index', 'Index'), ('COMPUTER', 'COMPUTER'), ('COMPUTER', 'COMPUTER'), ('COMPUTER', 'COMPUTER'), ('COMPUTER', 'COMPUTER'), ('COMPUTER', 'COMPUTER'), ('COMPUTER', 'COMPUTER'), ('COMPUTER', 'COMPUTER'), ('COMPUTER', 'COMPUTER'), ('COMPUTER', 'COMPUTER'), ('COMPUTER', 'COMPUTER'), ('COMPUTER', 'COMPUTER')], default='Index', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='headerimages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
