# Generated by Django 3.2.5 on 2021-07-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_site', '0009_auto_20210718_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerimages',
            name='PAGE',
            field=models.CharField(choices=[('MAIN', 'HOME PAGE'), ('AAC', 'ART AND CULTURAL CLUB'), ('COMP', 'COMPUTER CLUB'), ('DANCE', 'DANCE CLUB'), ('EM', 'EVENT MANAGEMENT CLUB'), ('LEGAL', 'LEGAL CLUB'), ('LIT', 'LITERATURE CLUB'), ('MEDIA', 'MEDIA CLUB'), ('MUSIC', 'MUSIC CLUB'), ('RAP', 'RESEARCH AND PRESENTATION CLUB'), ('ROBOT', 'ROBOTICS CLUB'), ('SOCIAL', 'SOCIAL CLUB'), ('SAD', 'SPEECH AND DEBATE CLUB')], default='MAIN', max_length=10),
        ),
    ]
