# Generated by Django 3.1.7 on 2022-01-15 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('committee_site', '0015_clubheads_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubheads',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='ClubHeads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clubheads',
            name='club',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clubheads',
            name='facebook_link',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='clubheads',
            name='instagram_link',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='clubheads',
            name='linkedin_link',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='clubheads',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
