# Generated by Django 3.1.7 on 2022-01-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_site', '0016_auto_20220115_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubheads',
            name='facebook_link',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='clubheads',
            name='instagram_link',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='clubheads',
            name='linkedin_link',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
