# Generated by Django 4.0.1 on 2022-01-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_site', '0018_notice_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
