# Generated by Django 4.0.1 on 2022-01-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_site', '0019_alter_notice_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Publisher', models.CharField(default=' ', max_length=100)),
                ('PublishDate', models.DateField(auto_now_add=True)),
                ('Image', models.ImageField(blank=True, upload_to='BlogImages')),
                ('Content', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='notice',
            name='time',
        ),
    ]
