# Generated by Django 4.0.1 on 2022-01-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_site', '0020_blogpost_remove_notice_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='Title',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
