# Generated by Django 4.0.1 on 2022-01-22 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committee_site', '0021_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Content',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(blank=True, upload_to='BlogImages')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee_site.blogpost')),
            ],
        ),
    ]
