# Generated by Django 4.0.1 on 2022-01-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee_site', '0022_alter_blogpost_content_blogimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='Image',
        ),
    ]
